# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
#        in_memory:
#            memory:
#                users:
#                    damien:
#                        password: azer
#                        roles: 'ROLE_USER'
#                   admin:
#                        password: azerty
#                       roles: 'ROLE_ADMIN'
        dbal:
            entity:
                class: GescomyBundle:User
                property: username
    encoders:
        GescomyBundle\Entity\User:
            algorithm: bcrypt
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            remember_me:
                secret:   '%secret%'
                lifetime: 604800 # 1 week in seconds
                path: /
            anonymous: ~
            provider: dbal
            form_login:
                login_path: login
                check_path: login
            logout:
                path:   /logout
                target: /
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_AUTHENTICATED_FULLY }
